"""
main.py — Campus Router Health 360
FastAPI backend with 3 core endpoints:
- GET /rankings: Worst-N routers with health scores
- GET /router/{router_id}: Detailed metrics, metadata, complaints, & score for a single router
- POST /copilot: Deterministic diagnosis + Claude API natural language phrasing
"""

import os
import sys
import json
from pathlib import Path
from typing import Optional

import requests
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

# Load environment variables from .env if present
load_dotenv()

# Add backend directory to sys.path to ensure module imports work seamlessly
sys.path.append(str(Path(__file__).resolve().parent.parent))

from app.data_loader import load_data
from app.scoring import compute_health_scores, get_worst_n
from app.diagnosis import diagnose_router, get_firmware_batch_flags

app = FastAPI(
    title="Campus Router Health 360 API",
    description="Backend API for router health monitoring, rankings, and AI copilot diagnostics.",
    version="1.0.0",
)

# Enable CORS for frontend integration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Global data state loaded on startup
routers_df, metrics_df, complaints_df = load_data()
scored_df = compute_health_scores(metrics_df)
firmware_stats = get_firmware_batch_flags(scored_df, routers_df)


class CopilotRequest(BaseModel):
    router_id: str
    question: Optional[str] = None


def _fallback_phrasing(diagnosis: dict) -> str:
    """Fallback natural language phrasing when Gemini API is unavailable or unconfigured."""
    cause = diagnosis.get("cause", "unknown")
    fix = diagnosis.get("fix", "check hardware")
    evidence = diagnosis.get("evidence", {})

    if cause == "firmware":
        fw = evidence.get("firmware_version", "unknown")
        aff = evidence.get("affected_router_count", 0)
        bad_hrs = evidence.get("this_router_bad_hour_count", 0)
        return (
            f"Router is running firmware {fw}, which is affected by a fleet-wide issue impacting {aff} routers. "
            f"This router recorded {bad_hrs} bad hours out of 24. "
            f"Recommended resolution is a firmware update."
        )
    elif cause == "user_side_issue":
        hs = evidence.get("health_score", 0.0)
        complaints = evidence.get("complaint_count", 0)
        return (
            f"Router metrics are healthy with a health score of {hs}, but it has {complaints} user complaints. "
            f"The issue is likely on the user side rather than hardware degradation. "
            f"Recommended action is user education."
        )
    elif cause == "placement_dead_zone":
        sig = evidence.get("avg_signal_dbm", 0.0)
        bldg = evidence.get("building", "N/A")
        rm = evidence.get("room", "N/A")
        return (
            f"Router has a weak average signal of {sig} dBm in {bldg} room {rm}. "
            f"The performance degradation is driven by coverage dead zones. "
            f"Recommended action is to relocate the router."
        )
    elif cause == "hardware_degradation":
        bad_hrs = evidence.get("bad_hour_count", 0)
        lat = evidence.get("avg_latency_ms", 0.0)
        return (
            f"Router exhibits sustained poor performance with {bad_hrs} bad hours and average latency of {lat}ms. "
            f"This indicates physical hardware degradation. "
            f"Recommended action is router replacement."
        )
    elif cause == "healthy":
        hs = evidence.get("health_score", 0.0)
        bad_hrs = evidence.get("bad_hour_count", 0)
        return (
            f"Router is operating normally with a health score of {hs} and only {bad_hrs} bad hours. "
            f"No corrective action is required."
        )
    else:
        return f"Router diagnosed with cause '{cause}'. Recommended action is {fix}."


def call_gemini_phrasing(diagnosis: dict, question: Optional[str] = None) -> str:
    """
    Calls the Gemini REST API directly (model gemini-2.0-flash) using requests.
    Passes ONLY the structured diagnosis JSON from diagnose_router().
    Asks the model to phrase a 2-3 sentence natural language answer using ONLY the numbers given.
    """
    gemini_api_key = os.environ.get("GEMINI_API_KEY")
    if not gemini_api_key:
        return _fallback_phrasing(diagnosis)

    diagnosis_json_str = json.dumps(diagnosis, indent=2)

    prompt = (
        f"You are an AI network copilot assisting campus IT administrators.\n"
        f"Below is a structured diagnostic report for a campus router generated by a deterministic diagnostic engine:\n\n"
        f"{diagnosis_json_str}\n\n"
        f"Task: Write a concise 2-3 sentence natural language explanation answering why this router is performing the way it is and what action to take.\n"
        f"CRITICAL CONSTRAINTS:\n"
        f"1. Use ONLY the numbers and facts given in the structured JSON above.\n"
        f"2. Do NOT invent, hallucinate, or infer any external numbers or metrics.\n"
        f"3. Keep the response to exactly 2-3 sentences."
    )
    if question:
        prompt += f"\nUser Question Context: {question}"

    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={gemini_api_key}"
    payload = {
        "contents": [
            {
                "parts": [
                    {"text": prompt}
                ]
            }
        ]
    }

    try:
        response = requests.post(
            url,
            json=payload,
            headers={"Content-Type": "application/json"},
            timeout=10,
        )
        if response.status_code == 200:
            data = response.json()
            text = data["candidates"][0]["content"]["parts"][0]["text"]
            return text.strip()
        else:
            print(f"Gemini API error ({response.status_code}): {response.text}")
            return _fallback_phrasing(diagnosis)
    except Exception as e:
        print(f"Gemini API request exception: {e}")
        return _fallback_phrasing(diagnosis)


def _round_floats(obj):
    """Recursively round all float values in a nested dict or list to 2 decimal places."""
    if isinstance(obj, float):
        return round(obj, 2)
    elif isinstance(obj, dict):
        return {k: _round_floats(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [_round_floats(v) for v in obj]
    return obj


@app.get("/")
def read_root():
    return {
        "status": "online",
        "service": "Campus Router Health 360 Backend",
        "endpoints": ["/rankings", "/router/{router_id}", "/copilot", "/firmware-stats"],
    }


@app.get("/rankings")
def get_rankings(limit: int = 10):
    """Returns worst-N routers ranked by health score (ascending)."""
    worst_df = get_worst_n(scored_df, n=limit)
    
    # Merge basic metadata (building, room, model, firmware_version) for UI convenience
    merged = worst_df.merge(
        routers_df[["router_id", "model", "firmware_version", "building", "room"]],
        on="router_id",
        how="left",
    )
    
    records = merged.to_dict(orient="records")
    raw_json = json.loads(json.dumps(records, default=str))
    clean_records = _round_floats(raw_json)
    return {
        "count": len(clean_records),
        "rankings": clean_records,
    }


@app.get("/firmware-stats")
def get_firmware_stats():
    """Returns list of firmware versions with affected_router_count, avg_bad_hour_count, avg_health_score, is_flagged."""
    stats_df = get_firmware_batch_flags(scored_df, routers_df)
    records = stats_df.to_dict(orient="records")
    raw_json = json.loads(json.dumps(records, default=str))
    return _round_floats(raw_json)


@app.get("/router/{router_id}")
def get_router_detail(router_id: str):
    """Returns single router details: metadata, health score metrics, complaints, and hourly readings."""
    router_score = scored_df[scored_df["router_id"] == router_id]
    if router_score.empty:
        raise HTTPException(status_code=404, detail=f"Router '{router_id}' not found")

    score_dict = router_score.iloc[0].to_dict()

    router_meta = routers_df[routers_df["router_id"] == router_id]
    meta_dict = router_meta.iloc[0].to_dict() if not router_meta.empty else {}

    router_complaints = complaints_df[complaints_df["router_id"] == router_id]
    complaints_list = router_complaints.to_dict(orient="records") if not router_complaints.empty else []

    router_metrics = metrics_df[metrics_df["router_id"] == router_id]
    metrics_list = router_metrics.to_dict(orient="records") if not router_metrics.empty else []

    result = {
        "router_id": router_id,
        "metadata": meta_dict,
        "score_details": score_dict,
        "complaints": complaints_list,
        "hourly_metrics": metrics_list,
    }
    raw_json = json.loads(json.dumps(result, default=str))
    return _round_floats(raw_json)


@app.post("/copilot")
def copilot_endpoint(req: CopilotRequest):
    """
    Evaluates rule-based diagnosis for the router, then passes structured JSON to Gemini REST API
    (model gemini-2.0-flash) for natural-language phrasing.
    """
    diagnosis = diagnose_router(
        router_id=req.router_id,
        scored_df=scored_df,
        routers_df=routers_df,
        complaints_df=complaints_df,
        firmware_stats=firmware_stats,
    )

    if diagnosis.get("note") == "router_id not found":
        raise HTTPException(status_code=404, detail=f"Router '{req.router_id}' not found")

    phrased_answer = call_gemini_phrasing(diagnosis, question=req.question)

    return {
        "router_id": req.router_id,
        "diagnosis": diagnosis,
        "phrased_answer": phrased_answer,
    }

